accounts:
  message: "Welcome to unknownBank accounts related prod APIs "
  contactDetails:
    name: "Mala Thirumoorthy - Product Owner"
    email: "mals@unknonwbank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384