accounts:
  message: "Welcome to bank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@unknownbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345